# Generated by Django 4.2.20 on 2025-06-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkbox_for_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkboxsetting', models.CharField(max_length=100)),
                ('temperature', models.BooleanField(default=True)),
                ('humidity', models.BooleanField(default=True)),
                ('cane_brand', models.BooleanField(default=True)),
                ('harvest_year', models.BooleanField(default=True)),
                ('gouging_machine', models.BooleanField(default=True)),
                ('cane_diamater', models.BooleanField(default=True)),
                ('thicness', models.BooleanField(default=True)),
                ('hardness', models.BooleanField(default=True)),
                ('flexibility', models.BooleanField(default=True)),
                ('density', models.BooleanField(default=True)),
                ('shaper', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reedsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.BooleanField(default=True)),
                ('humidity', models.BooleanField(default=True)),
                ('cane_brand', models.BooleanField(default=True)),
                ('harvest_year', models.BooleanField(default=True)),
                ('gouging_machine', models.BooleanField(default=True)),
                ('cane_diamater', models.BooleanField(default=True)),
                ('thicness', models.BooleanField(default=True)),
                ('hardness', models.BooleanField(default=True)),
                ('flexibility', models.BooleanField(default=True)),
                ('density', models.BooleanField(default=True)),
                ('shaper', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
