# Generated by Django 4.2.20 on 2025-06-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='cane_brand',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='cane_diamater',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='density',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='flexibility',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='gouging_machine',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='hardness',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='harvest_year',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='shaper',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='thicness',
        ),
    ]
