# Generated by Django 4.2.20 on 2025-06-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_remove_checkbox_for_setting_cane_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checkbox_for_setting',
            name='updated_at',
        ),
    ]
