# Generated by Django 4.2.20 on 2025-06-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersettings', '0003_remove_checkbox_for_setting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox_for_setting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
